/**
 * tokens.js
 * Shared token extraction from theme.json settings and SCSS variables.
 *
 * TOKEN_CATEGORIES defines every named preset array in theme.json that has a
 * slug+value pair. Each entry maps:
 *   - jsonPath      : path through the settings object to the array
 *   - slugKey       : the property name used as the slug (always "slug")
 *   - valueKey      : the property name that holds the value
 *   - scssPrefix    : prepended to slug when forming the SCSS variable name
 *                     (empty string = match existing ct-variables.scss convention)
 *   - wpCssVarFn    : function(slug) → the CSS custom property WordPress generates
 *
 * NOTE: spacing uses `spacingScale` (auto-generated by WordPress at runtime).
 * Those preset slugs (20–80) exist only as CSS vars at runtime; they are not
 * enumerated in settings.json, so they are excluded from sync. They appear in
 * the diff report as a notice rather than conflicts.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Token category definitions
// ─────────────────────────────────────────────────────────────────────────────

export const TOKEN_CATEGORIES = [
  {
    id: 'color',
    label: 'Color Palette',
    jsonPath: ['settings', 'color', 'palette'],
    slugKey: 'slug',
    valueKey: 'color',
    scssPrefix: '', // keeps existing convention: $dark-blue (no prefix)
    wpCssVarFn: (slug) => `--wp--preset--color--${slug}`,
  },
  {
    id: 'fontSize',
    label: 'Font Sizes',
    jsonPath: ['settings', 'typography', 'fontSizes'],
    slugKey: 'slug',
    valueKey: 'size',
    scssPrefix: 'font-size-', // $font-size-body
    wpCssVarFn: (slug) => `--wp--preset--font-size--${slug}`,
  },
  {
    id: 'fontFamily',
    label: 'Font Families',
    jsonPath: ['settings', 'typography', 'fontFamilies'],
    slugKey: 'slug',
    valueKey: 'fontFamily',
    scssPrefix: 'font-family-', // $font-family-gabarito
    wpCssVarFn: (slug) => `--wp--preset--font-family--${slug}`,
  },
  {
    id: 'shadow',
    label: 'Shadow Presets',
    jsonPath: ['settings', 'shadow', 'presets'],
    slugKey: 'slug',
    valueKey: 'shadow',
    scssPrefix: 'shadow-', // $shadow-card
    wpCssVarFn: (slug) => `--wp--preset--shadow--${slug}`,
  },
  {
    id: 'borderRadius',
    label: 'Border Radii',
    jsonPath: ['settings', 'border', 'radiusSizes'],
    slugKey: 'slug',
    valueKey: 'size',
    scssPrefix: 'radius-', // $radius-small
    wpCssVarFn: (slug) => `--wp--preset--border-radius--${slug}`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// JSON token extraction
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extract all preset tokens from a parsed settings.json object.
 *
 * @param {object} settingsJson - The full parsed JSON (with top-level "settings" key)
 * @returns {Map<string, JsonToken>}
 *
 * @typedef {object} JsonToken
 * @property {string} key         - Unique key: "<categoryId>:<slug>"
 * @property {string} category    - category id string
 * @property {string} slug        - The token slug
 * @property {string} value       - The raw preset value
 * @property {string} scssVarName - e.g. "$dark-blue" or "$font-size-body"
 * @property {string} wpCssVar    - e.g. "--wp--preset--color--dark-blue"
 */
export function extractJsonTokens(settingsJson) {
  const tokens = new Map();

  for (const category of TOKEN_CATEGORIES) {
    const array = getNestedValue(settingsJson, category.jsonPath);
    if (!Array.isArray(array)) continue;

    for (const entry of array) {
      const slug = entry[category.slugKey];
      const value = entry[category.valueKey];
      if (!slug || value === undefined || value === null) continue;

      const scssVarName = `$${category.scssPrefix}${slug}`;
      const key = `${category.id}:${slug}`;

      tokens.set(key, {
        key,
        category: category.id,
        categoryLabel: category.label,
        slug,
        value: value.toString().trim().replace(/;$/, ''), // strip trailing ; (e.g. shadow values in JSON)
        scssVarName,
        wpCssVar: category.wpCssVarFn(slug),
      });
    }
  }

  return tokens;
}

// ─────────────────────────────────────────────────────────────────────────────
// SCSS variable extraction
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extract all SCSS variable declarations from a .scss file's content.
 *
 * Handles:
 *   $var-name: value;           → plain declaration
 *   $var-name: value; // comment
 *   $var-name: value !default;  → !default flag is stripped
 *
 * Multi-line values and nested rules are NOT parsed (ct-variables.scss
 * uses only single-line declarations).
 *
 * @param {string} scssContent
 * @returns {Map<string, ScssToken>}  keyed by variable name (without $)
 *
 * @typedef {object} ScssToken
 * @property {string} varName    - Variable name without "$"
 * @property {string} value      - Raw value string
 * @property {string} line       - Full original line text
 * @property {number} lineIndex  - 0-based line number in file
 * @property {string|null} comment - Inline comment text, if any
 */
export function extractScssTokens(scssContent) {
  const tokens = new Map();
  const lines = scssContent.split('\n');

  // Matches:  $name: value; or $name: value !default; + optional // comment
  const VAR_RE = /^\s*\$([a-zA-Z0-9_-]+)\s*:\s*(.+?)\s*(?:!(?:default|global))?\s*;\s*(?:\/\/(.*))?$/;

  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(VAR_RE);
    if (!match) continue;

    const varName = match[1];
    const value = match[2].trim();
    const comment = match[3]?.trim() ?? null;

    tokens.set(varName, {
      varName,
      value,
      line: lines[i],
      lineIndex: i,
      comment,
    });
  }

  return tokens;
}

// ─────────────────────────────────────────────────────────────────────────────
// Utility
// ─────────────────────────────────────────────────────────────────────────────

/** Traverse a nested object with an array of property keys. */
export function getNestedValue(obj, pathArray) {
  return pathArray.reduce((acc, key) => acc?.[key], obj);
}

/**
 * Look up which category owns a given SCSS variable name.
 * Returns { category, slug } or null if not recognized.
 */
export function categoryForScssVar(varName) {
  for (const cat of TOKEN_CATEGORIES) {
    if (cat.scssPrefix === '') {
      // Colors: slug IS the var name (e.g. $dark-blue → slug "dark-blue")
      return { category: cat, slug: varName };
    } else if (varName.startsWith(cat.scssPrefix)) {
      const slug = varName.slice(cat.scssPrefix.length);
      return { category: cat, slug };
    }
  }
  return null;
}

/**
 * Normalize a token value for equality comparison:
 *   - lowercase
 *   - collapse internal whitespace (hsl(42, 53%, 90%) === hsl(42,53%,90%))
 *   - strip trailing semicolons
 */
export function normalizeValue(val) {
  if (val === undefined || val === null) return '';
  return val
    .toString()
    .trim()
    .toLowerCase()
    .replace(/\s*,\s*/g, ', ')
    .replace(/\s+/g, ' ')
    .replace(/;$/, '');
}
