<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_69c3515383d9f',
		'title' => 'Class Details 🎓',
		'fields' => array(
			array(
				'key' => 'field_69c351691e998',
				'label' => 'Program',
				'name' => 'program',
				'aria-label' => '',
				'type' => 'acfe_taxonomy_terms',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => array(
					0 => 'program',
				),
				'allow_terms' => array(
					0 => 'all_program',
				),
				'allow_level' => '',
				'field_type' => 'checkbox',
				'min' => '',
				'max' => '',
				'default_value' => array(),
				'return_format' => 'name',
				'layout' => 'horizontal',
				'toggle' => 0,
				'save_terms' => 1,
				'load_terms' => 1,
				'allow_in_bindings' => 0,
				'choices' => array(),
				'ui' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'search_placeholder' => '',
				'allow_custom' => 0,
				'other_choice' => 0,
			),
			array(
				'key' => 'field_69c35153ffe5e',
				'label' => 'Session',
				'name' => 'session',
				'aria-label' => '',
				'type' => 'acfe_taxonomy_terms',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => array(
					0 => 'session',
				),
				'allow_terms' => '',
				'allow_level' => '',
				'field_type' => 'checkbox',
				'min' => '',
				'max' => '',
				'default_value' => array(),
				'return_format' => 'name',
				'layout' => 'horizontal',
				'toggle' => 0,
				'save_terms' => 1,
				'load_terms' => 1,
				'allow_in_bindings' => 0,
				'choices' => array(),
				'ui' => 0,
				'multiple' => 0,
				'allow_null' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'search_placeholder' => '',
				'allow_custom' => 0,
				'other_choice' => 0,
			),
			array(
				'key' => 'field_69e19b14ef1ad',
				'label' => 'Teaching Artist',
				'name' => 'teaching_artist',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'Attach artist profile.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'artist',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'post_tag:teaching-artist',
				),
				'return_format' => 'id',
				'multiple' => 1,
				'min' => '',
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
			),
			array(
				'key' => 'field_69c3532b1e99c',
				'label' => 'Taught by...',
				'name' => 'taught_by',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Display text for class information.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_69c352671e999',
				'label' => 'Date Start',
				'name' => 'date_start',
				'aria-label' => '',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'F j, Y',
				'return_format' => 'Ymd',
				'first_day' => 1,
				'default_to_current_date' => 0,
				'placeholder' => '',
				'min_date' => '',
				'max_date' => '',
				'no_weekends' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_69c352861e99a',
				'label' => 'Date End',
				'name' => 'date_end',
				'aria-label' => '',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'F j, Y',
				'return_format' => 'Ymd',
				'first_day' => 1,
				'default_to_current_date' => 0,
				'placeholder' => '',
				'min_date' => '',
				'max_date' => '',
				'no_weekends' => 0,
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_69e19d9aa7d92',
				'label' => 'Registration Link',
				'name' => 'registration_link',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_69c352bf1e99b',
				'label' => 'Day of Week',
				'name' => 'class_day',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'monday' => 'Monday',
					'tuesday' => 'Tuesday',
					'wednesday' => 'Wednesday',
					'thursday' => 'Thursday',
					'friday' => 'Friday',
					'saturday' => 'Saturday',
					'sunday' => 'Sunday',
				),
				'default_value' => false,
				'return_format' => 'label',
				'multiple' => 0,
				'max' => '',
				'prepend' => '',
				'append' => '',
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'create_options' => 0,
				'save_options' => 0,
				'allow_custom' => 0,
				'search_placeholder' => '',
				'min' => '',
			),
			array(
				'key' => 'field_69d9db059fdf1',
				'label' => 'Time Start',
				'name' => 'time_start',
				'aria-label' => '',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'g:i a',
				'return_format' => 'g:i a',
				'placeholder' => '',
				'min_time' => '09:00',
				'max_time' => '22:00',
				'min_hour' => '',
				'max_hour' => '',
				'min_min' => 0,
				'max_min' => '',
				'min_sec' => '',
				'max_sec' => '',
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_69e19ad2d1e16',
				'label' => 'Time End',
				'name' => 'time_end',
				'aria-label' => '',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'g:i a',
				'return_format' => 'g:i a',
				'placeholder' => '',
				'min_time' => '08:00',
				'max_time' => '23:00',
				'min_hour' => '',
				'max_hour' => '',
				'min_min' => '',
				'max_min' => '',
				'min_sec' => '',
				'max_sec' => '',
				'allow_in_bindings' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'class',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
		'display_title' => '',
		'allow_ai_access' => false,
		'ai_description' => '',
		'acfe_autosync' => array(
			0 => 'php',
			1 => 'json',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1776468371,
	));

endif;
