<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69ec80e948a54',
	'title' => 'Nav Colors 🎨',
	'fields' => array(
		array(
			'key' => 'field_69ec80e9c4e0e',
			'label' => 'Onstage',
			'name' => 'onstage_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 1,
			'return_format' => 'string',
			'acfe_advanced' => 1,
			'display' => 'palette',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 1,
			'theme_colors' => 1,
			'colors' => array(
			),
			'allow_in_bindings' => 0,
			'custom_palette_source' => '',
			'palette_colors' => '',
			'show_color_wheel' => true,
			'button_label' => 'Select Color',
		),
		array(
			'key' => 'field_69ec815dc4e0f',
			'label' => 'Join',
			'name' => 'join_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 1,
			'return_format' => 'string',
			'acfe_advanced' => 1,
			'display' => 'palette',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 1,
			'theme_colors' => 1,
			'colors' => array(
			),
			'allow_in_bindings' => 0,
			'custom_palette_source' => '',
			'palette_colors' => '',
			'show_color_wheel' => true,
			'button_label' => 'Select Color',
		),
		array(
			'key' => 'field_69ec8164c4e10',
			'label' => 'Donate',
			'name' => 'donate_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 1,
			'return_format' => 'string',
			'acfe_advanced' => 1,
			'display' => 'palette',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 1,
			'theme_colors' => 1,
			'colors' => array(
			),
			'allow_in_bindings' => 0,
			'custom_palette_source' => '',
			'palette_colors' => '',
			'show_color_wheel' => true,
			'button_label' => 'Select Color',
		),
		array(
			'key' => 'field_69ec818fcfc40',
			'label' => 'Education',
			'name' => 'education_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 1,
			'return_format' => 'string',
			'acfe_advanced' => 1,
			'display' => 'palette',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 1,
			'theme_colors' => 1,
			'colors' => array(
			),
			'allow_in_bindings' => 0,
			'custom_palette_source' => '',
			'palette_colors' => '',
			'show_color_wheel' => true,
			'button_label' => 'Select Color',
		),
		array(
			'key' => 'field_69ec81c0cfc42',
			'label' => 'Backstage',
			'name' => 'backstage_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 1,
			'return_format' => 'string',
			'acfe_advanced' => 1,
			'display' => 'palette',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 1,
			'theme_colors' => 1,
			'colors' => array(
			),
			'allow_in_bindings' => 0,
			'custom_palette_source' => '',
			'palette_colors' => '',
			'show_color_wheel' => true,
			'button_label' => 'Select Color',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'site-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set main menu section colors.',
	'show_in_rest' => 1,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
	'modified' => 1781991050,
	'acfe' => array(
		'autosync' => array(
			0 => 'php',
			1 => 'json',
		),
	),
));

endif;