<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_event_details',
	'title' => 'Event Details 📅',
	'fields' => array(
		array(
			'key' => 'field_69d9c04caeecb',
			'label' => 'Date 📆',
			'name' => 'date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'm/d/Y',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'no_weekends' => 0,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_event_date_start',
			'label' => 'Start ⏳',
			'name' => 'start',
			'aria-label' => '',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'H:i:s',
			'placeholder' => '',
			'min_time' => '9:00',
			'max_time' => '23:59',
			'min_hour' => '',
			'max_hour' => '',
			'min_min' => '',
			'max_min' => '',
			'min_sec' => '',
			'max_sec' => '',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_event_date_end',
			'label' => 'End⌛',
			'name' => 'end',
			'aria-label' => '',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'H:i:s',
			'placeholder' => '',
			'min_time' => '9:00',
			'max_time' => '23:59',
			'min_hour' => '',
			'max_hour' => '',
			'min_min' => '',
			'max_min' => '',
			'min_sec' => '',
			'max_sec' => '',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_event_ticketing_link',
			'label' => 'Buy Tickets Link',
			'name' => 'ticketing-link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_event_is_promo',
			'label' => 'Promotional Event?',
			'name' => 'is-promo',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'style' => '',
		),
		array(
			'key' => 'field_event_venue',
			'label' => 'Venue',
			'name' => 'venue',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Required if no production selected.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'ct-venue',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'max' => '',
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_add_post' => 0,
			'acfe_edit_post' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
			'min' => '',
		),
		array(
			'key' => 'field_event_venue_room',
			'label' => 'BATAC Room',
			'name' => 'venue-room',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Required',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_event_venue',
						'operator' => '==contains',
						'value' => 'Bette Aitken Theater Arts Center',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				': Inherit from Production' => ': Inherit from Production',
				'offsite' => 'Offsite',
				'cripe' => 'Cripe Stage',
				'fydamar' => 'Fyda-Mar Stage',
				'classroom' => 'Classroom',
				'lobby' => 'Lobby',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'max' => '',
			'prepend' => '',
			'append' => '',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
			'allow_custom' => 0,
			'search_placeholder' => '',
			'min' => '',
		),
		array(
			'key' => 'field_69dc850729c3f',
			'label' => 'test',
			'name' => 'test',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'placeholder' => '',
			'min_date' => '',
			'max_date' => '',
			'min_time' => '',
			'max_time' => '',
			'no_weekends' => 0,
			'min_hour' => '',
			'max_hour' => '',
			'min_min' => '',
			'max_min' => '',
			'min_sec' => '',
			'max_sec' => '',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69efcafc97627',
			'label' => 'Related Production',
			'name' => 'production',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'ct-production',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'max' => '',
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_add_post' => 0,
			'acfe_edit_post' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => false,
				'acfe_bidirectional_related' => false,
			),
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
			'min' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'ct-event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1777322794,
));

endif;