<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_69d9a4e3b3e3d',
		'title' => 'Season Details',
		'fields' => array(
			array(
				'key' => 'field_69db2d99999ff',
				'label' => 'Season Info',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'no_preference' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69d9b65f7163e',
				'label' => 'Hide Season?',
				'name' => 'hide-season',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'style' => '',
			),
			array(
				'key' => 'field_69d9aba6c722e',
				'label' => 'Season Image',
				'name' => 'season_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'array',
				'library' => 'all',
				'upload_folder' => '',
				'acfe_thumbnail' => 0,
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_69d9a5ccd8c93',
				'label' => 'Resident Playwright',
				'name' => 'resident_playwright',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'artist',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
				'min' => '',
			),
			array(
				'key' => 'field_69db2bdb51580',
				'label' => 'Related Page',
				'name' => 'related_page',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 0,
				'acfe_edit_post' => 0,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
				'min' => '',
			),
			array(
				'key' => 'field_69d9af27a7034',
				'label' => 'Season Producers',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'no_preference' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69d9b54271632',
				'label' => 'Season Producers',
				'name' => 'season_producers',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '45',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'supporter',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 1,
				'min' => '',
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
			),
			array(
				'key' => 'field_69db2df699a00',
				'label' => 'Associate Season Producers',
				'name' => 'associate_season_producers',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '45',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'supporter',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 1,
				'min' => '',
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
			),
			array(
				'key' => 'field_69d9b6a67163f',
				'label' => 'Season Producer Message',
				'name' => 'season_producer_message',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'acfe_wysiwyg_height' => 300,
				'acfe_wysiwyg_max_height' => '',
				'acfe_wysiwyg_valid_elements' => '',
				'acfe_wysiwyg_custom_style' => '',
				'acfe_wysiwyg_disable_wp_style' => 0,
				'acfe_wysiwyg_autoresize' => 0,
				'acfe_wysiwyg_disable_resize' => 0,
				'acfe_wysiwyg_remove_path' => 0,
				'acfe_wysiwyg_menubar' => 0,
				'acfe_wysiwyg_transparent' => 0,
				'acfe_wysiwyg_merge_toolbar' => 0,
				'acfe_wysiwyg_custom_toolbar' => 0,
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
				'acfe_wysiwyg_auto_init' => 0,
				'acfe_wysiwyg_min_height' => 300,
				'acfe_wysiwyg_toolbar_buttons' => array(),
			),
			array(
				'key' => 'field_69db2d8a999fe',
				'label' => 'OTR Sponsors',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'no_preference' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69db2fe2d71e8',
				'label' => 'OTR Sponsors Main',
				'name' => 'otr_sponsors_main',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'Appears larger and first.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'supporter',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
				'min' => '',
			),
			array(
				'key' => 'field_69d9b5fc7163c',
				'label' => 'OTR Sponsors',
				'name' => 'otr_sponsors',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'supporter',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 1,
				'min' => '',
				'max' => '',
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(),
				'save_post_type' => '',
			),
			array(
				'key' => 'field_69d9af60a7035',
				'label' => 'OTR Sponsors Alt',
				'name' => 'otr_sponsors_alt',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'acfe_wysiwyg_height' => 300,
				'acfe_wysiwyg_max_height' => '',
				'acfe_wysiwyg_valid_elements' => '',
				'acfe_wysiwyg_custom_style' => '',
				'acfe_wysiwyg_disable_wp_style' => 1,
				'acfe_wysiwyg_autoresize' => 0,
				'acfe_wysiwyg_disable_resize' => 0,
				'acfe_wysiwyg_remove_path' => 0,
				'acfe_wysiwyg_menubar' => 0,
				'acfe_wysiwyg_transparent' => 0,
				'acfe_wysiwyg_merge_toolbar' => 0,
				'acfe_wysiwyg_custom_toolbar' => 0,
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
				'acfe_wysiwyg_auto_init' => 0,
				'acfe_wysiwyg_min_height' => 300,
				'acfe_wysiwyg_toolbar_buttons' => array(),
			),
			array(
				'key' => 'field_69d9af0683d3b',
				'label' => 'Season Productions',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'no_preference' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69d9ae34b0885',
				'label' => 'Main Series',
				'name' => 'main_series',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'production',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'series:main',
				),
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'return_format' => 'id',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 1,
				'elements' => array(
					0 => 'featured_image',
				),
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key' => 'field_69d9aeab83d37',
				'label' => 'OTR Series',
				'name' => 'otr_series',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'production',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'series:otr',
				),
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'return_format' => 'id',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 1,
				'elements' => array(
					0 => 'featured_image',
				),
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key' => 'field_69d9aec883d39',
				'label' => 'TYA Series',
				'name' => 'tya_series',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'production',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'series:tya',
				),
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'return_format' => 'id',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 1,
				'elements' => array(
					0 => 'featured_image',
				),
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key' => 'field_69d9aebb83d38',
				'label' => 'Holiday Series',
				'name' => 'holiday_series',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'production',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'series:otr',
				),
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'return_format' => 'id',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 1,
				'elements' => array(
					0 => 'featured_image',
				),
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key' => 'field_69d9aef283d3a',
				'label' => 'Visiting Companies',
				'name' => 'visiting_companies',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'production',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'series:otr',
				),
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'return_format' => 'id',
				'acfe_add_post' => 1,
				'acfe_edit_post' => 1,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '1',
					'acfe_bidirectional_related' => '',
				),
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 1,
				'elements' => array(
					0 => 'featured_image',
				),
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'season',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'tooltip',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
		'display_title' => '',
		'allow_ai_access' => false,
		'ai_description' => '',
		'acfe_autosync' => array(
			0 => 'php',
			1 => 'json',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1776645157,
	));

endif;
