<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_artist_profile',
	'title' => 'Artist Profile 👤',
	'fields' => array(
		array(
			'key' => 'field_artist_profession',
			'label' => 'Profession',
			'name' => 'profession',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'General vocation or discipline (e.g. Actor, Lighting Designer, Director, etc.)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c1c5de76fad',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Specific title (e.g. General Manager)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c494ca5a869',
			'label' => '',
			'name' => 'artist_tags',
			'aria-label' => '',
			'type' => 'acfe_taxonomy_terms',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => array(
				0 => 'post_tag',
			),
			'allow_terms' => array(
				0 => '597',
				1 => '639',
				2 => '644',
			),
			'allow_level' => '',
			'field_type' => 'checkbox',
			'min' => '',
			'max' => '',
			'default_value' => array(
			),
			'return_format' => 'id',
			'layout' => 'vertical',
			'toggle' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'allow_in_bindings' => 0,
			'choices' => array(
			),
			'ui' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'search_placeholder' => '',
			'allow_custom' => 0,
			'other_choice' => 0,
		),
		array(
			'key' => 'field_69d9d14885127',
			'label' => 'Links',
			'name' => 'artist_links',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69d9d15b85128',
					'label' => 'Link Name',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69d9d14885127',
				),
				array(
					'key' => 'field_69d9d16585129',
					'label' => 'Link URL',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_69d9d14885127',
				),
			),
		),
		array(
			'key' => 'field_69c4a2039c576',
			'label' => 'Resident Artist Title',
			'name' => 'resident_artist_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Alt Resident Artist title, if blank defaults to title',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_69c494ca5a869',
						'operator' => '==contains',
						'value' => '644',
					),
				),
				array(
					array(
						'field' => 'field_69c494ca5a869',
						'operator' => '==contains',
						'value' => 'Resident Artist',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69d9d5d3361db',
			'label' => 'Teaching Bio',
			'name' => 'teaching_bio',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Shows on Teaching Artists page, defaults to regular bio if blank.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_69c494ca5a869',
						'operator' => '==contains',
						'value' => '639',
					),
				),
				array(
					array(
						'field' => 'field_69c494ca5a869',
						'operator' => '==contains',
						'value' => 'Teaching Artist',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_wysiwyg_height' => 300,
			'acfe_wysiwyg_max_height' => '',
			'acfe_wysiwyg_valid_elements' => '',
			'acfe_wysiwyg_custom_style' => '',
			'acfe_wysiwyg_disable_wp_style' => 0,
			'acfe_wysiwyg_autoresize' => 0,
			'acfe_wysiwyg_disable_resize' => 0,
			'acfe_wysiwyg_remove_path' => 0,
			'acfe_wysiwyg_menubar' => 0,
			'acfe_wysiwyg_transparent' => 0,
			'acfe_wysiwyg_merge_toolbar' => 0,
			'acfe_wysiwyg_custom_toolbar' => 1,
			'acfe_wysiwyg_toolbar_buttons' => array(
				'acfe_wysiwyg_toolbar_1' => array(
					array(
						'acfe_wysiwyg_toolbar_row' => 'bold',
					),
					array(
						'acfe_wysiwyg_toolbar_row' => 'italic',
					),
					array(
						'acfe_wysiwyg_toolbar_row' => 'bullist',
					),
					array(
						'acfe_wysiwyg_toolbar_row' => 'numlist',
					),
					array(
						'acfe_wysiwyg_toolbar_row' => 'link',
					),
					array(
						'acfe_wysiwyg_toolbar_row' => 'spellchecker',
					),
					array(
						'acfe_wysiwyg_toolbar_row' => 'fullscreen',
					),
				),
				'acfe_wysiwyg_toolbar_2' => '',
				'acfe_wysiwyg_toolbar_3' => '',
				'acfe_wysiwyg_toolbar_4' => '',
			),
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'acfe_wysiwyg_auto_init' => 0,
			'acfe_wysiwyg_min_height' => 300,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'artist',
			),
		),
	),
	'menu_order' => -10,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => array(
		0 => 'author',
		1 => 'categories',
		2 => 'comments',
		3 => 'discussion',
		4 => 'excerpt',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'visibility',
		8 => 'preview',
		9 => 'send-trackbacks',
		10 => 'slug',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe' => array(
		'autosync' => array(
			0 => 'php',
			1 => 'json',
		),
		'meta' => array(
			array(
				'key' => '',
				'value' => '',
			),
			array(
				'key' => '',
				'value' => '',
			),
		),
	),
	'modified' => 1781991049,
));

endif;