<?php

// Unregister Ollie patterns & Pattern Categories
function chance_unregister_ollie_patterns()
{
  // Unregister all patterns registered by the Ollie parent theme
  $ollie_patterns = array(
    'ollie/author-box',
    'ollie/big-text-call-to-action-card',
    'ollie/blog-page',
    'ollie/blog-post-card',
    'ollie/blog-post-columns',
    'ollie/blog-post-columns-single',
    'ollie/call-to-action-card-with-buttons',
    'ollie/card-call-to-action',
    'ollie/card-contact',
    'ollie/card-pricing-table-dark',
    'ollie/card-testimonial',
    'ollie/card-text-and-call-to-action',
    'ollie/contact-details',
    'ollie/details-card',
    'ollie/faq',
    'ollie/feature-boxes-with-button',
    'ollie/feature-boxes-with-icon-dark',
    'ollie/features-with-emojis',
    'ollie/footer-dark',
    'ollie/footer-dark-centered',
    'ollie/footer-dark-minimal',
    'ollie/footer-light',
    'ollie/footer-light-centered',
    'ollie/footer-light-minimal',
    'ollie/header-dark',
    'ollie/header-dark-with-banner',
    'ollie/header-dark-with-buttons',
    'ollie/header-light',
    'ollie/header-light-with-banner',
    'ollie/header-light-with-buttons',
    'ollie/hero-call-to-action-buttons',
    'ollie/hero-call-to-action-buttons-light',
    'ollie/hero-dark',
    'ollie/hero-light',
    'ollie/hero-text-image-and-logos',
    'ollie/image-and-numbered-features',
    'ollie/image-and-text-card',
    'ollie/job-openings',
    'ollie/large-text-and-text-boxes',
    'ollie/lead-magnet-card',
    'ollie/menu-card-1',
    'ollie/menu-card-2',
    'ollie/menu-card-3',
    'ollie/menu-card-4',
    'ollie/menu-panel-1',
    'ollie/menu-panel-2',
    'ollie/menu-panel-3',
    'ollie/menu-panel-4',
    'ollie/menu-panel-5',
    'ollie/menu-panel-6',
    'ollie/mobile-menu-1',
    'ollie/mobile-menu-2',
    'ollie/mobile-menu-3',
    'ollie/mobile-menu-4',
    'ollie/mobile-menu-5',
    'ollie/mobile-menu-6',
    'ollie/numbers',
    'ollie/numbers-stacked',
    'ollie/page-about',
    'ollie/page-download',
    'ollie/page-features',
    'ollie/page-home',
    'ollie/page-pricing',
    'ollie/post-comments',
    'ollie/post-list-card',
    'ollie/post-loop-grid',
    'ollie/post-loop-grid-default',
    'ollie/post-loop-list',
    'ollie/pricing-table',
    'ollie/pricing-table-3-column',
    'ollie/pricing-table-card',
    'ollie/pricing-table-with-testimonials',
    'ollie/profile-box',
    'ollie/single-testimonial',
    'ollie/social-profile-card',
    'ollie/team-members',
    'ollie/template-index-grid',
    'ollie/template-index-list',
    'ollie/template-page-404',
    'ollie/template-page-archive',
    'ollie/template-page-centered',
    'ollie/template-page-full',
    'ollie/template-page-left-sidebar',
    'ollie/template-page-right-sidebar',
    'ollie/template-page-search',
    'ollie/template-page-wide',
    'ollie/template-post-centered',
    'ollie/template-post-left-sidebar',
    'ollie/template-post-right-sidebar',
    'ollie/template-post-sticky',
    'ollie/template-post-wide',
    'ollie/testimonial-highlight',
    'ollie/testimonials-and-logos',
    'ollie/testimonials-with-big-text',
    'ollie/testimonials-with-social-links',
    'ollie/text-and-details-card',
    'ollie/text-and-image-columns-with-icons',
    'ollie/text-and-image-columns-with-testimonial',
    'ollie/text-box-with-link-card',
    'ollie/text-call-to-action',
    'ollie/text-call-to-action-buttons',
    'ollie/woo-cart',
    'ollie/woo-checkout',
    'ollie/woo-coming-soon',
    'ollie/woo-header',
    'ollie/woo-order-confirmation',
    'ollie/woo-product-archive',
    'ollie/woo-product-archive-sidebar',
    'ollie/woo-product-card',
    'ollie/woo-product-card-2',
    'ollie/woo-product-card-3',
    'ollie/woo-product-card-4',
    'ollie/woo-product-card-5',
    'ollie/woo-product-search',
    'ollie/woo-single-product',
  );

  foreach ($ollie_patterns as $pattern) {
    unregister_block_pattern($pattern);
  }

  // Unregister Ollie pattern categories
  $ollie_categories = array(
    'ollie/call-to-action',
    'ollie/features',
    'ollie/hero',
    'ollie/pages',
    'ollie/posts',
    'ollie/pricing',
    'ollie/testimonial',
    'footer',
    'header',
  );

  foreach ($ollie_categories as $category) {
    unregister_block_pattern_category($category);
  }
}
// add_action('init', 'chance_unregister_ollie_patterns', 20);


function chance_register_block_patterns()
{
  $pattern_dir = get_stylesheet_directory() . '/patterns';
  $patterns = array(
    'about-speak-up' => array(
      'title'       => __('About Speak Up', 'chance-ollie'),
      'description' => __('About section for Speak Up', 'chance-ollie'),
      'categories'  => array('banner'),
      'synced'      => true,
    ),
    'annual-fund' => array(
      'title'       => __('Annual Fund', 'chance-ollie'),
      'description' => __('Annual Fund Sponsorship Table', 'chance-ollie'),
      'categories'  => array('tables'),
      'synced'      => true,
    ),
    'annual-fund-donor-benefits' => array(
      'title'       => __('Annual Fund Donor Benefits', 'chance-ollie'),
      'description' => __('Benefits for annual fund donors', 'chance-ollie'),
      'categories'  => array('cta'),
      'synced'      => true,
    ),
    'artist-fund' => array(
      'title'       => __('Artist Fund', 'chance-ollie'),
      'description' => __('Artist Fund Sponsorship Table', 'chance-ollie'),
      'categories'  => array('tables'),
      'synced'      => true,
    ),
    'blog-feed' => array(
      'title'       => __('Blog Feed', 'chance-ollie'),
      'description' => __('Blog posts query loop', 'chance-ollie'),
      'categories'  => array('query'),
      'synced'      => true,
    ),
    'card-excerpt-date-terms' => array(
      'title'       => __('Card Excerpt Date Terms', 'chance-ollie'),
      'description' => __('Card with excerpt, date, and terms', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'card-headshot' => array(
      'title'       => __('Card Headshot', 'chance-ollie'),
      'description' => __('Headshot card layout', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'chance-media-text' => array(
      'title'       => __('Chance Media Text', 'chance-ollie'),
      'description' => __('Media and text layout', 'chance-ollie'),
      'categories'  => array('section'),
      'synced'      => true,
    ),
    'choose-your-ticket-type' => array(
      'title'       => __('Choose Your Ticket Type', 'chance-ollie'),
      'description' => __('Ticket type selection CTA', 'chance-ollie'),
      'categories'  => array('cta'),
      'synced'      => true,
    ),
    'community-partners' => array(
      'title'       => __('Community Partners', 'chance-ollie'),
      'description' => __('Community partners card grid', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'corporate-sponsorship' => array(
      'title'       => __('Corporate Sponsorship', 'chance-ollie'),
      'description' => __('Corporate Sponsorship Table', 'chance-ollie'),
      'categories'  => array('tables'),
      'synced'      => true,
    ),
    'detailed-class-card' => array(
      'title'       => __('Detailed Class Card', 'chance-ollie'),
      'description' => __('Card with detailed class information', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'donor-benefits' => array(
      'title'       => __('Donor Benefits', 'chance-ollie'),
      'description' => __('Benefits section for donors', 'chance-ollie'),
      'categories'  => array('cta'),
      'synced'      => true,
    ),
    'education-outreach-fund' => array(
      'title'       => __('Education Outreach Fund', 'chance-ollie'),
      'description' => __('Education Outreach Fund Sponsorship Table', 'chance-ollie'),
      'categories'  => array('tables'),
      'synced'      => true,
    ),
    'headshot-card-mini-grid' => array(
      'title'       => __('Headshot Card Mini Grid', 'chance-ollie'),
      'description' => __('Mini grid of headshot cards', 'chance-ollie'),
      'categories'  => array('grid'),
      'synced'      => true,
    ),
    'home-grid-shortcode-version' => array(
      'title'       => __('Home Grid Shortcode Version', 'chance-ollie'),
      'description' => __('Home grid layout with shortcodes', 'chance-ollie'),
      'categories'  => array('grid'),
      'synced'      => true,
    ),
    'latest-posts' => array(
      'title'       => __('Latest Posts', 'chance-ollie'),
      'description' => __('Query loop for latest posts', 'chance-ollie'),
      'categories'  => array('query'),
      'synced'      => true,
    ),
    'masthead-page' => array(
      'title'       => __('Masthead Page', 'chance-ollie'),
      'description' => __('Page masthead header', 'chance-ollie'),
      'categories'  => array('page-header'),
      'synced'      => true,
    ),
    'masthead-title-banner' => array(
      'title'       => __('Masthead Title Banner', 'chance-ollie'),
      'description' => __('Hero banner with masthead title', 'chance-ollie'),
      'categories'  => array('banner'),
      'synced'      => true,
    ),
    'membership-benefits' => array(
      'title'       => __('Membership Benefits (thumbnail list)', 'chance-ollie'),
      'categories'  => array('membership'),
      'synced'      => true,
    ),
    'membership-button-trio' => array(
      'title'       => __('Membership Button Trio', 'chance-ollie'),
      'description' => __('Three button group for membership options', 'chance-ollie'),
      'categories'  => array('button'),
      'synced'      => true,
    ),
    // 'membership-levels-benefits-table' => array(
    //   'title'       => __('Membership Levels Benefits Table', 'chance-ollie'),
    //   'description' => __('Table comparing membership levels and benefits', 'chance-ollie'),
    //   'categories'  => array('tables'),
    //   'synced'      => true,
    // ),
    'mini-card-2' => array(
      'title'       => __('Mini Card 2', 'chance-ollie'),
      'description' => __('Small card layout version 2', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    // 'need-more-convincing' => array(
    //   'title'       => __('Need More Convincing', 'chance-ollie'),
    //   'description' => __('Additional call to action', 'chance-ollie'),
    //   'categories'  => array('cta'),
    //   'synced'      => true,
    // ),
    'notes-default' => array(
      'title'       => __('Notes Default', 'chance-ollie'),
      'description' => __('Default Notes Pattern', 'chance-ollie'),
      'categories'  => array('production'),
      'synced'      => true,
    ),
    'otr-new-works-fund' => array(
      'title'       => __('OTR New Works Fund', 'chance-ollie'),
      'description' => __('OTR New Works Fund Sponsorship Table', 'chance-ollie'),
      'categories'  => array('tables'),
      'synced'      => true,
    ),
    'otr-series-sponsors' => array(
      'title'       => __('OTR Series Sponsors', 'chance-ollie'),
      'description' => __('Sponsors for OTR series', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'our-donors' => array(
      'title'       => __('Our Donors', 'chance-ollie'),
      'description' => __('Grid of donor information', 'chance-ollie'),
      'categories'  => array('grid','section'),
      'synced'      => true,
    ),
    'page-header' => array(
      'title'       => __('Page Header', 'chance-ollie'),
      'description' => __('Standard page header pattern', 'chance-ollie'),
      'categories'  => array('page-header'),
      'synced'      => true,
    ),
    'performances' => array(
      'title'       => __('Performances', 'chance-ollie'),
      'description' => __('Production performances listing', 'chance-ollie'),
      'categories'  => array('production'),
      'synced'      => true,
    ),
    'post-card' => array(
      'title'       => __('Post Card', 'chance-ollie'),
      'description' => __('Individual post card', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'post-card-2' => array(
      'title'       => __('Post Card 2', 'chance-ollie'),
      'description' => __('Post card layout version 2', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'post-cover-card-basic' => array(
      'title'       => __('Post Cover Card Basic', 'chance-ollie'),
      'description' => __('Basic post card with cover image', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'producers-circle' => array(
      'title'       => __('Producers Circle', 'chance-ollie'),
      'description' => __('Producers Circle Sponsorship Table', 'chance-ollie'),
      'categories'  => array('tables'),
      'synced'      => true,
    ),
    'production-card-full-details' => array(
      'title'       => __('Production Card Full Details', 'chance-ollie'),
      'description' => __('Detailed production information card', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'production-page-header' => array(
      'title'       => __('Production Page Header', 'chance-ollie'),
      'description' => __('Header for production pages', 'chance-ollie'),
      'categories'  => array('page-header'),
      'synced'      => true,
    ),
    'production-tile' => array(
      'title'       => __('Production Tile', 'chance-ollie'),
      'description' => __('Production tile card layout', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'questions-donation' => array(
      'title'       => __('Questions Donation', 'chance-ollie'),
      'description' => __('FAQ for donation questions', 'chance-ollie'),
      'categories'  => array('faq'),
      'synced'      => true,
    ),
    'questions-education' => array(
      'title'       => __('Questions Education', 'chance-ollie'),
      'description' => __('FAQ for education questions', 'chance-ollie'),
      'categories'  => array('faq'),
      'synced'      => true,
    ),
    'questions-members' => array(
      'title'       => __('Questions Members', 'chance-ollie'),
      'description' => __('FAQ for member questions', 'chance-ollie'),
      'categories'  => array('faq'),
      'synced'      => true,
    ),
    'questions-veterans' => array(
      'title'       => __('Questions Veterans', 'chance-ollie'),
      'description' => __('FAQ for veteran questions', 'chance-ollie'),
      'categories'  => array('faq'),
      'synced'      => true,
    ),
    'quotes-via-bindings' => array(
      'title'       => __('Quotes Via Bindings', 'chance-ollie'),
      'description' => __('Quote carousel with bindings', 'chance-ollie'),
      'categories'  => array('media'),
      'synced'      => true,
    ),
    'ready-to-become-a-chance-member' => array(
      'title'       => __('Ready to Become a Chance Member', 'chance-ollie'),
      'description' => __('Call to action to become a member', 'chance-ollie'),
      'categories'  => array('cta'),
      'synced'      => true,
    ),
    'related-pages' => array(
      'title'       => __('Related Pages', 'chance-ollie'),
      'description' => __('Grid of related pages', 'chance-ollie'),
      'categories'  => array('grid'),
      'synced'      => true,
    ),
    'relaxed-performances' => array(
      'title'       => __('Relaxed Performances', 'chance-ollie'),
      'description' => __('Relaxed performances information', 'chance-ollie'),
      'categories'  => array('production'),
      'synced'      => true,
    ),
    'season-banner' => array(
      'title'       => __('Season Banner', 'chance-ollie'),
      'description' => __('Banner for season announcement', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'season-header' => array(
      'title'       => __('Season Header', 'chance-ollie'),
      'description' => __('Header for season pages', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'season-page' => array(
      'title'       => __('Season Page', 'chance-ollie'),
      'description' => __('Full season page layout', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'season-page-v3' => array(
      'title'       => __('Season Page V3', 'chance-ollie'),
      'description' => __('Season page layout version 3', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'season-query-row' => array(
      'title'       => __('Season Query Row', 'chance-ollie'),
      'description' => __('Row of season query results', 'chance-ollie'),
      'categories'  => array('query'),
      'synced'      => true,
    ),
    'season-row-series' => array(
      'title'       => __('Season Row Series', 'chance-ollie'),
      'description' => __('Row of series for a season', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'season-rows' => array(
      'title'       => __('Season Rows', 'chance-ollie'),
      'description' => __('Multiple rows of season content', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'series-buttons' => array(
      'title'       => __('Series Buttons', 'chance-ollie'),
      'description' => __('Button Group for Series Selection', 'chance-ollie'),
      'categories'  => array('button'),
      'synced'      => true,
    ),
    'series-page' => array(
      'title'       => __('Series Page', 'chance-ollie'),
      'description' => __('Full series page layout', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'shared-annual-fund-benefits' => array(
      'title'       => __('Shared Annual Fund Benefits', 'chance-ollie'),
      'description' => __('Shared benefits for annual fund', 'chance-ollie'),
      'categories'  => array('cta'),
      'synced'      => true,
    ),
    'simple-card-grid' => array(
      'title'       => __('Simple Card Grid', 'chance-ollie'),
      'description' => __('Simple grid of cards', 'chance-ollie'),
      'categories'  => array('grid'),
      'synced'      => true,
    ),
    'subscribe-buy-more-button-trio' => array(
      'title'       => __('Subscribe Buy More Button Trio', 'chance-ollie'),
      'description' => __('Three buttons for subscribe and buy options', 'chance-ollie'),
      'categories'  => array('button'),
      'synced'      => true,
    ),
    'subscribe-cta-banner' => array(
      'title'       => __('Subscribe CTA Banner', 'chance-ollie'),
      'description' => __('Call to action banner for subscriptions', 'chance-ollie'),
      'categories'  => array('banner'),
      'synced'      => true,
    ),
    'supporter-grid' => array(
      'title'       => __('Supporter Grid', 'chance-ollie'),
      'description' => __('Grid layout for supporters', 'chance-ollie'),
      'categories'  => array('grid'),
      'synced'      => true,
    ),
    'theater-for-young-audience-series' => array(
      'title'       => __('Theater for Young Audience Series', 'chance-ollie'),
      'description' => __('TYA series information', 'chance-ollie'),
      'categories'  => array('season'),
      'synced'      => true,
    ),
    'ticket-faq' => array(
      'title'       => __('Ticket FAQ', 'chance-ollie'),
      'description' => __('Frequently asked questions about tickets', 'chance-ollie'),
      'categories'  => array('faq'),
      'synced'      => true,
    ),
    'tiny-card' => array(
      'title'       => __('Tiny Card', 'chance-ollie'),
      'description' => __('Minimal card layout', 'chance-ollie'),
      'categories'  => array('card'),
      'synced'      => true,
    ),
    'title-banner' => array(
      'title'       => __('Title Banner (simple)', 'chance-ollie'),
      'description' => __('Banner with title text', 'chance-ollie'),
      'categories'  => array('banner'),
      'synced'      => true,
    ),
    'video-trailer' => array(
      'title'       => __('Video Trailer', 'chance-ollie'),
      'description' => __('Video Trailer Pattern', 'chance-ollie'),
      'categories'  => array('media'),
      'synced'      => true,
    ),
  );

  foreach ($patterns as $slug => $properties) {
    $pattern_file = $pattern_dir . '/' . $slug . '.html';

    if (file_exists($pattern_file)) {
      $content = file_get_contents($pattern_file);
      if ($content !== false) {
        $pattern_properties = array_merge(
          $properties,
          array(
            'content' => $content,
          )
        );
        register_block_pattern('chance-ollie/' . $slug, $pattern_properties);
      }
    }
  }
}
// add_action('init', 'chance_register_block_patterns', 21);
